from general_rec.predictors.GitHubLabelPredictor import GitHubLabelPredictor
from general_rec.predictors.GeneralLabelPredictor import GeneralLabelPredictor
from general_rec.predictors.MultiLabelClassifierPredictor import MultiLabelClassifierPredictor